############# English navigation ##############

# main menu

[[main]]
name = "home"
url = ""
weight = 1

[[main]]
name = "blog"
url = "blog/"
weight = 3

  [[main]]
  parent= "blog"
  name = "tech"
  url = "categories/tech"

  [[main]]
  parent= "blog"
  name = "career"
  url = "categories/career"


[[main]]
name = "contributions"
url = "contributions/"
weight = 4

  [[main]]
  parent= "contributions"
  name = "Speaking"
  url = "contributions/speaking"
  weight = 1

  [[main]]
  parent= "contributions"
  name = "Events"
  url = "contributions/events"
  weight = 2

  [[main]]
  parent= "contributions"
  name = "Open Source"
  url = "contributions/open-source"
  weight = 3


[[main]]
name = "about"
url = "about/"
weight = 5

[[main]]
name = "contact"
url = "contact/"
weight = 6
